// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCode.Template
{
    using System.Data;
    using System;
    
    
    #line 1 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class EntityTemplate : EntityTemplateBase
    {
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing Core.EntityCore;\r\n\r\n");
            
            #line 8 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

	if(NameSpace =="")
	{

            
            #line default
            #line hidden
            this.Write("namespace Common\r\n");
            
            #line 13 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 18 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write(".Common\r\n");
            
            #line 19 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("{\r\n\t[Serializable]\r\n\tpublic class ");
            
            #line 24 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityClassName));
            
            #line default
            #line hidden
            this.Write(" : EntityBase\r\n\t{\r\n\t\tpublic ");
            
            #line 26 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(" TableSchema\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn (");
            
            #line 30 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(")_tableSchema;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic ");
            
            #line 34 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityClassName));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\t_tableSchema = ");
            
            #line 36 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(".Current;\r\n\t\t}\r\n\r\n\t\t#region 属性列表\r\n\t\t");
            
            #line 40 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

		    foreach (DataRow row in DtColunms.Rows)
			{
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 45 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ConvertDbType(row["TypeName"].ToString())));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 45 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["ColunmName"].ToString().Substring(0, 1).ToUpper() + row["ColunmName"].ToString().Substring(1).ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\r\n\t\t\t");
            
            #line 48 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

				if(Config.ConvertDbType(row["TypeName"].ToString())=="string")
				{
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n\t\t\tget{ return Convert.To");
            
            #line 53 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ConvertDbType(row["TypeName"].ToString()).Replace("?","").Replace("s","S")));
            
            #line default
            #line hidden
            this.Write("(GetData(");
            
            #line 53 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(".C_");
            
            #line 53 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["ColunmName"].ToString()));
            
            #line default
            #line hidden
            this.Write("));} \r\n\r\n\t\t\t");
            
            #line 55 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

				}
				else
				{
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tget{ return GetData<");
            
            #line 61 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ConvertDbType(row["TypeName"].ToString()).Replace("?","")));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 61 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(".C_");
            
            #line 61 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["ColunmName"].ToString()));
            
            #line default
            #line hidden
            this.Write("); }\r\n\t\t\t\r\n\t\t\t");
            
            #line 63 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

				}
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tset{ SetData(");
            
            #line 67 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableClassName));
            
            #line default
            #line hidden
            this.Write(".C_");
            
            #line 67 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["ColunmName"].ToString()));
            
            #line default
            #line hidden
            this.Write(", value); }\r\n\t\t}\r\n\r\n\t\t");
            
            #line 70 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"

			}
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 78 "E:\AutoCode\AutoCode\Template\EntityTemplate.tt"


		public string NameSpace
		{
			set;
			get;
		}

        public string TableName
        {
			set;
            get;
        }

        public DataTable DtColunms
        {
			set;
            get;
        }

        public string EntityClassName
        {
            get
            {
                return TableName.Replace("_", "") + "Entity";
            }
        }

        public string TableClassName
        {
            get
            {
                return TableName.Replace("_", "") + "Table";
            }
        }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class EntityTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
